-- SmartBilling Migration 009: Plastic Recycling Phase 6 Procurement, Vendor & Purchase Intelligence
-- Purpose: Add specialized ERP tables for Purchase Requisitions, Supplier Quotations,
--          Purchase Orders, Purchase Deliveries, Supplier Performance, Rate Intelligence, and MRP.
-- Safety: IDEMPOTENT, NON-DESTRUCTIVE, NO DROPS, NO MODIFICATION OF EXISTING PRODUCTION DATA

-- 1. Purchase Requisitions Table
CREATE TABLE IF NOT EXISTS plastic_purchase_requisitions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  pr_no VARCHAR(50) NOT NULL,
  request_date DATE NOT NULL,
  requester_name VARCHAR(150) NOT NULL,
  department VARCHAR(100) NOT NULL DEFAULT 'Procurement',
  priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
  required_date DATE NULL,
  notes TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  approved_by INT NULL,
  approved_at DATETIME NULL,
  rejection_reason TEXT NULL,
  created_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_company_pr_no (company_id, pr_no),
  INDEX idx_pr_company_id (company_id),
  INDEX idx_pr_status (status),
  INDEX idx_pr_priority (priority),
  INDEX idx_pr_request_date (request_date),
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (approved_by) REFERENCES admins(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
);

-- 2. Purchase Requisition Items Table
CREATE TABLE IF NOT EXISTS plastic_purchase_requisition_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  requisition_id INT NOT NULL,
  raw_material_id INT NOT NULL,
  requested_qty DECIMAL(12,2) NOT NULL,
  unit VARCHAR(20) NOT NULL DEFAULT 'KG',
  estimated_rate DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  estimated_total DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  requirement_reason VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_pr_items_company_id (company_id),
  INDEX idx_pr_items_req_id (requisition_id),
  INDEX idx_pr_items_material_id (raw_material_id),
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (requisition_id) REFERENCES plastic_purchase_requisitions(id) ON DELETE CASCADE,
  FOREIGN KEY (raw_material_id) REFERENCES raw_materials(id) ON DELETE RESTRICT
);

-- 3. Supplier Quotations Table
CREATE TABLE IF NOT EXISTS plastic_supplier_quotations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  quotation_no VARCHAR(50) NOT NULL,
  supplier_id INT NOT NULL,
  requisition_id INT NULL,
  quotation_date DATE NOT NULL,
  validity_date DATE NULL,
  reference_no VARCHAR(100) NULL,
  payment_terms VARCHAR(100) NULL,
  delivery_terms VARCHAR(100) NULL,
  lead_time_days INT NOT NULL DEFAULT 0,
  subtotal DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  freight_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  grand_total DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  notes TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  created_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_company_quote_no (company_id, quotation_no),
  INDEX idx_quote_company_id (company_id),
  INDEX idx_quote_supplier_id (supplier_id),
  INDEX idx_quote_requisition_id (requisition_id),
  INDEX idx_quote_status (status),
  INDEX idx_quote_date (quotation_date),
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
  FOREIGN KEY (requisition_id) REFERENCES plastic_purchase_requisitions(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
);

-- 4. Supplier Quotation Items Table
CREATE TABLE IF NOT EXISTS plastic_supplier_quotation_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  quotation_id INT NOT NULL,
  raw_material_id INT NOT NULL,
  quantity DECIMAL(12,2) NOT NULL,
  unit VARCHAR(20) NOT NULL DEFAULT 'KG',
  rate DECIMAL(10,2) NOT NULL,
  discount_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  tax_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  freight_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(14,2) NOT NULL,
  effective_landed_rate DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_quote_items_company_id (company_id),
  INDEX idx_quote_items_quote_id (quotation_id),
  INDEX idx_quote_items_material_id (raw_material_id),
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (quotation_id) REFERENCES plastic_supplier_quotations(id) ON DELETE CASCADE,
  FOREIGN KEY (raw_material_id) REFERENCES raw_materials(id) ON DELETE RESTRICT
);

-- 5. Purchase Orders Table
CREATE TABLE IF NOT EXISTS plastic_purchase_orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  po_no VARCHAR(50) NOT NULL,
  supplier_id INT NOT NULL,
  quotation_id INT NULL,
  requisition_id INT NULL,
  po_date DATE NOT NULL,
  expected_delivery_date DATE NULL,
  payment_terms VARCHAR(100) NULL,
  delivery_terms VARCHAR(100) NULL,
  shipping_address TEXT NULL,
  notes TEXT NULL,
  subtotal DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  freight_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  grand_total DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  approved_by INT NULL,
  approved_at DATETIME NULL,
  created_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_company_po_no (company_id, po_no),
  INDEX idx_po_company_id (company_id),
  INDEX idx_po_supplier_id (supplier_id),
  INDEX idx_po_status (status),
  INDEX idx_po_date (po_date),
  INDEX idx_po_expected_date (expected_delivery_date),
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
  FOREIGN KEY (quotation_id) REFERENCES plastic_supplier_quotations(id) ON DELETE SET NULL,
  FOREIGN KEY (requisition_id) REFERENCES plastic_purchase_requisitions(id) ON DELETE SET NULL,
  FOREIGN KEY (approved_by) REFERENCES admins(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
);

-- 6. Purchase Order Items Table
CREATE TABLE IF NOT EXISTS plastic_purchase_order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  purchase_order_id INT NOT NULL,
  raw_material_id INT NOT NULL,
  ordered_qty DECIMAL(12,2) NOT NULL,
  unit VARCHAR(20) NOT NULL DEFAULT 'KG',
  rate DECIMAL(10,2) NOT NULL,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  tax_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(14,2) NOT NULL,
  received_qty DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  pending_qty DECIMAL(12,2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_po_items_company_id (company_id),
  INDEX idx_po_items_po_id (purchase_order_id),
  INDEX idx_po_items_material_id (raw_material_id),
  INDEX idx_po_items_status (status),
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (purchase_order_id) REFERENCES plastic_purchase_orders(id) ON DELETE CASCADE,
  FOREIGN KEY (raw_material_id) REFERENCES raw_materials(id) ON DELETE RESTRICT
);

-- 7. Purchase Deliveries Table
CREATE TABLE IF NOT EXISTS plastic_purchase_deliveries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  delivery_no VARCHAR(50) NOT NULL,
  purchase_order_id INT NOT NULL,
  purchase_order_item_id INT NULL,
  truck_inward_id INT NULL,
  purchase_bill_id INT NULL,
  supplier_id INT NOT NULL,
  raw_material_id INT NOT NULL,
  delivery_date DATE NOT NULL,
  expected_date DATE NULL,
  challan_no VARCHAR(100) NULL,
  truck_number VARCHAR(50) NULL,
  delivered_qty DECIMAL(12,2) NOT NULL,
  accepted_qty DECIMAL(12,2) NOT NULL,
  rejected_qty DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  delivery_delay_days INT NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'DELIVERED',
  notes TEXT NULL,
  created_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_company_delivery_no (company_id, delivery_no),
  INDEX idx_del_company_id (company_id),
  INDEX idx_del_po_id (purchase_order_id),
  INDEX idx_del_supplier_id (supplier_id),
  INDEX idx_del_material_id (raw_material_id),
  INDEX idx_del_truck_inward (truck_inward_id),
  INDEX idx_del_purchase_bill (purchase_bill_id),
  INDEX idx_del_date (delivery_date),
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (purchase_order_id) REFERENCES plastic_purchase_orders(id) ON DELETE CASCADE,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
  FOREIGN KEY (raw_material_id) REFERENCES raw_materials(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
);

-- 8. Supplier Performance Table
CREATE TABLE IF NOT EXISTS plastic_supplier_performance (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  supplier_id INT NOT NULL,
  period_month INT NOT NULL,
  period_year INT NOT NULL,
  total_orders INT NOT NULL DEFAULT 0,
  total_purchase_value DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  on_time_deliveries INT NOT NULL DEFAULT 0,
  late_deliveries INT NOT NULL DEFAULT 0,
  total_ordered_qty DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_received_qty DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_rejected_qty DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  quality_acceptance_percent DECIMAL(5,2) NOT NULL DEFAULT 100.00,
  average_purchase_rate DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  outstanding_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  delivery_score DECIMAL(5,2) NOT NULL DEFAULT 100.00,
  quality_score DECIMAL(5,2) NOT NULL DEFAULT 100.00,
  commercial_score DECIMAL(5,2) NOT NULL DEFAULT 100.00,
  overall_score DECIMAL(5,2) NOT NULL DEFAULT 100.00,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_company_supp_period (company_id, supplier_id, period_year, period_month),
  INDEX idx_supp_perf_company (company_id),
  INDEX idx_supp_perf_supplier (supplier_id),
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
);

-- 9. Purchase Rate History Table
CREATE TABLE IF NOT EXISTS plastic_purchase_rate_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  raw_material_id INT NOT NULL,
  supplier_id INT NOT NULL,
  purchase_bill_id INT NULL,
  purchase_order_id INT NULL,
  purchase_date DATE NOT NULL,
  purchase_rate DECIMAL(10,2) NOT NULL,
  effective_landed_rate DECIMAL(10,2) NOT NULL,
  quantity DECIMAL(12,2) NOT NULL,
  previous_rate DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  variance_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  variance_percent DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_rate_hist_company (company_id),
  INDEX idx_rate_hist_material (raw_material_id),
  INDEX idx_rate_hist_supplier (supplier_id),
  INDEX idx_rate_hist_date (purchase_date),
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (raw_material_id) REFERENCES raw_materials(id) ON DELETE RESTRICT,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT
);

-- 10. Material Requirements Planning Table
CREATE TABLE IF NOT EXISTS plastic_material_requirements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  raw_material_id INT NOT NULL,
  calculation_date DATE NOT NULL,
  current_stock DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  minimum_stock DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  maximum_stock DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  reserved_stock DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  available_stock DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  monthly_consumption_avg DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  suggested_order_qty DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  urgency_level VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_mrp_company (company_id),
  INDEX idx_mrp_material (raw_material_id),
  INDEX idx_mrp_urgency (urgency_level),
  INDEX idx_mrp_status (status),
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (raw_material_id) REFERENCES raw_materials(id) ON DELETE CASCADE
);
